export const DIFICULTAD = { FACIL: 'FACIL', MEDIO: 'MEDIO', DIFICIL: 'DIFICIL' }
export const ROLE = { ALUMNO: 'ALUMNO', PROFESOR: 'PROFESOR', ADMIN: 'ADMIN' }
export const SESSION_ESTADO = { EN_CURSO: 'EN_CURSO', COMPLETADA: 'COMPLETADA', ABANDONADA: 'ABANDONADA' }
export const RARIDAD = { COMUN: 'COMUN', RARO: 'RARO', EPICO: 'EPICO', LEGENDARIO: 'LEGENDARIO' }

export const MULTIPLICADOR_DIFICULTAD = { FACIL: 1.0, MEDIO: 1.5, DIFICIL: 2.0 }
export const XP_POR_NIVEL = 200
export const PENALIZACION_PISTA = 0.5
export const ESTRELLAS_THRESHOLDS = { tres: 90, dos: 60 } // % de aciertos

export const DEFAULT_CANTIDAD_EJERCICIOS = 10
export const MAX_EJERCICIOS_POR_SESION = 30
export const DIAS_EVITAR_REPETICION = 7
export const ITEMS_PER_PAGE = 20
